# micro-bit base image
# See more about resin base images here: http://docs.resin.io/runtime/resin-base-images/
FROM joe4465/micro-bit

# Set the working directory
WORKDIR /usr/src/app

# Copy config files to the working directory
COPY config.json module.json ./

# Copy source files to the working directory
COPY source/ ./source

# Compile the firmware
CMD yt build && \
    mv build/bbc-microbit-classic-gcc/source/micro-bit-combined.hex /out/
